### ISSUE TITLE
md2docbook.pl handling of double-space+newline

### ISSUE THREAD

**Issue by debdrup** [freebsd/freebsd-quarterly#190]
MarkDown supports a syntax with double-space+newline leading to a new line being created without inserting a new paragraph, as [shown here](https://github.com/freebsd/freebsd-quarterly/blob/master/2020q1/foundation.md#general)
Talking with salvadore@ on IRC, it sounds as if md2docbook.pl doesn't handle this appropriately, and it sounds like the fix it to have it insert a simple <br /> for the doublespace+newline syntax.

**Comment by lsalvadore** [comment]
Thanks, debdrup! I will fix it soon.

**Comment by lsalvadore** [comment]
Fixed! Thanks debdrup for reporting.
