### ISSUE TITLE
Possible typo in Foundation report

### ISSUE THREAD

**Issue by pauamma** [freebsd/freebsd-quarterly#269]
> Open system call path handling support for O_BENEATH, O_RESLOVE_BENEATH

Shouldn't that last one be O_RESOLVE_BENEATH instead?

**Comment by debdrup** [comment]
You're absolutely right, and it's been fixed with https://github.com/freebsd/freebsd-quarterly/commit/df89eff9cc31b3e4a837eec1d29aa63dbfec736d

**Comment by emaste** [comment]
Thank you!
