### ISSUE TITLE
2020q4/embedded-lab.md nits

### ISSUE THREAD

**Issue by pauamma** [freebsd/freebsd-quarterly#294]
Submitting this as an issue instead of a pull request because I'm not sure for the first what exactly was meant, and the last may not be an error at all.

- "have a basic set of FreeBSD installed that matches the board." Possible fixes: s/FreeBSD/FreeBSD packages/ or s/set of // (or, if neither is applicable, perhaps explain what "a basic set" means here)
- "with a environment due to power issues" s/ a / an /
- "opt-isolated" s/opt/opto/ maybe?

**Comment by debdrup** [comment]
Thanks for this, it's good that you brought up - especially the latter one, because I read that understanding what I meant, but didn't others might not pick up on the meaning as readily as I did.

**Comment by pauamma** [comment]
It's unclear to me whether the original submitter meant "optionally" or "optically" as I thought. Optically isolated interfaces (also called "opto-isolated", see eg https://en.wikipedia.org/wiki/Opto-isolator) are familiar to me from my days as an embedded systems guy way back when, but OTOH I'm unfamiliar with USB, so your reading may very well be accurate. Perhaps we should check with the submitter?
