### ISSUE TITLE
Missing RSS feed

### ISSUE THREAD

**Issue by dwt** [freebsd/freebsd-quarterly#322]
Not sure this is the right place to report this, but I have been unable to locate an RSS feed for the reports - but would very much like to have one.

Can you please advise where the right place to make such a bug report would be?￼

Thanks in advance

**Comment by debdrup** [comment]
There isn't one.

There is [one for the FreeBSD project as a whole](https://www.freebsd.org/news/rss.xml), though.

This repo is just for working on the quarterly reports - so if you want to file something, it should be on [the FreeBSD bug tracker](bugs.freebsd.org/).

**Comment by dwt** [comment]
[x] done https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=252876
