### ISSUE TITLE
Policy regarding links in description

### ISSUE THREAD

**Issue by smortex** [freebsd/freebsd-quarterly#52]
Hey!

Historically, status reports had a link section before the actual status report text, and no links in the status report text itself.  I think it was a limitation due to the XML files we had to generate to send status reports.

Does this limitation still applies, or are we free to use the markdown markup to add links to the text of new status reports (like [this one](https://github.com/freebsd/freebsd-quarterly/tree/master/2019q1))?

**Comment by trasz** [comment]
No, we can handle inline links just fine.  You might take a look at eg https://github.com/freebsd/freebsd-quarterly/blob/master/2018q4/nosh.md.
